
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gleea
 */
public class PizzaDecoratorUI extends javax.swing.JFrame {

    /**
     * Creates new form PizzaDecoratorUI
     */
    public PizzaDecoratorUI() {

        initComponents();
    }
public static int getSum(){
        int rowsCount = diytable.getRowCount();
        int sum = 0;
        for(int i = 0; i < rowsCount; i++){
            sum = sum+Integer.parseInt(diytable.getValueAt(i, 2).toString());
        }
        boolean b = six.isSelected();
        boolean c = nine.isSelected();
        boolean a = twelve.isSelected();
        if(b==true){
        sum+=10;
        }
        if(c==true){
        sum+=20;
        }
        if(a==true){
        sum+=30;
        }
        return sum;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        as = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        asparagus = new javax.swing.JSpinner();
        chorizo = new javax.swing.JSpinner();
        bo = new javax.swing.JSpinner();
        on = new javax.swing.JSpinner();
        gb = new javax.swing.JSpinner();
        rb = new javax.swing.JSpinner();
        ham = new javax.swing.JSpinner();
        spinach = new javax.swing.JSpinner();
        chicken = new javax.swing.JSpinner();
        pc = new javax.swing.JSpinner();
        fc = new javax.swing.JSpinner();
        bacon = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diytable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        six = new javax.swing.JRadioButton();
        deep = new javax.swing.JRadioButton();
        crispy = new javax.swing.JRadioButton();
        diytotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        twelve = new javax.swing.JRadioButton();
        nine = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(983, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DO-IT-YOURSELF");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 170, 36);

        as.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chorizo.png"))); // NOI18N
        as.setText("jLabel2");
        getContentPane().add(as);
        as.setBounds(200, 80, 103, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chicken.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 260, 83, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bs.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 260, 63, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pc27.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 260, 80, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asparugus32.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 70, 100, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bo.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 80, 80, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gp.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 170, 90, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 170, 80, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hp.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 160, 90, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/item2.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 170, 100, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/item326.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 80, 80, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/x45.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 260, 90, 50);

        asparagus.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(asparagus);
        asparagus.setBounds(140, 90, 40, 30);

        chorizo.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(chorizo);
        chorizo.setBounds(300, 90, 40, 30);

        bo.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(bo);
        bo.setBounds(430, 90, 40, 30);

        on.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(on);
        on.setBounds(560, 90, 40, 30);

        gb.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(gb);
        gb.setBounds(140, 180, 40, 30);

        rb.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(rb);
        rb.setBounds(300, 180, 40, 30);

        ham.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(ham);
        ham.setBounds(430, 180, 40, 30);

        spinach.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(spinach);
        spinach.setBounds(560, 180, 40, 30);

        chicken.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(chicken);
        chicken.setBounds(140, 270, 40, 30);

        pc.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(pc);
        pc.setBounds(300, 270, 40, 30);

        fc.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(fc);
        fc.setBounds(430, 270, 40, 30);

        bacon.setModel(new javax.swing.SpinnerNumberModel(1, 0, 5, 1));
        getContentPane().add(bacon);
        bacon.setBounds(560, 270, 40, 30);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("asparagus");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 130, 70, 14);

        jLabel15.setText("chorizo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(230, 130, 50, 14);

        jLabel16.setText("black olives");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(360, 130, 80, 14);

        jLabel17.setText("onions");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(500, 130, 50, 14);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("green bellpepper");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 220, 120, 14);

        jLabel19.setText("red bellpepper");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(200, 220, 100, 14);

        jLabel20.setText("ham");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(380, 220, 60, 14);

        jLabel21.setText("spinach");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(500, 220, 60, 14);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("chicken");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(70, 310, 100, 14);

        jLabel23.setText("parmeshan cheese");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(200, 310, 130, 14);

        jLabel24.setText("feta cheese");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(360, 310, 90, 14);

        jLabel25.setText("bacon");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(500, 310, 60, 14);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 310, 50, 21);

        diytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qty", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(diytable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(650, 100, 280, 240);

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setText("CREATE PIZZA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 380, 180, 30);

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton2.setText("DONE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 380, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 130, 50, 21);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 130, 50, 21);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setText("add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(420, 130, 50, 21);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setText("add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(550, 130, 50, 21);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton8.setText("add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 220, 50, 21);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton9.setText("add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(290, 220, 50, 21);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton10.setText("add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(420, 220, 50, 21);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton11.setText("add");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(550, 220, 50, 21);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton12.setText("add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(130, 310, 50, 21);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton13.setText("add");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(290, 310, 50, 21);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton14.setText("add");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(420, 310, 50, 21);

        jButton15.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jButton15.setText("Remove");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(650, 340, 80, 25);

        buttonGroup1.add(six);
        six.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        six.setSelected(true);
        six.setText("6\"");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six);
        six.setBounds(450, 380, 43, 30);

        buttonGroup2.add(deep);
        deep.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        deep.setForeground(new java.awt.Color(255, 255, 255));
        deep.setText("Deep Crust");
        getContentPane().add(deep);
        deep.setBounds(790, 60, 120, 30);

        buttonGroup2.add(crispy);
        crispy.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        crispy.setForeground(new java.awt.Color(255, 255, 255));
        crispy.setSelected(true);
        crispy.setText("Cripsy Base");
        crispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crispyActionPerformed(evt);
            }
        });
        getContentPane().add(crispy);
        crispy.setBounds(650, 60, 120, 30);

        diytotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diytotalActionPerformed(evt);
            }
        });
        getContentPane().add(diytotal);
        diytotal.setBounds(840, 340, 90, 30);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setText("Total");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(810, 340, 34, 30);

        jLabel27.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel27.setText("Each toppings   $20");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(180, 20, 160, 40);

        buttonGroup1.add(twelve);
        twelve.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        twelve.setText("12\"");
        twelve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveActionPerformed(evt);
            }
        });
        getContentPane().add(twelve);
        twelve.setBounds(550, 380, 50, 30);

        buttonGroup1.add(nine);
        nine.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nine.setText("9\"");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine);
        nine.setBounds(500, 380, 43, 30);

        jLabel28.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Size");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(390, 380, 60, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("$10     $20    $30");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(460, 360, 140, 20);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diy.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 980, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        diytotal.setText(Integer.toString(getSum()));
        boolean b = six.isSelected();
        boolean c = nine.isSelected();
        int qty=1;
        int ftotal = Integer.parseInt(diytotal.getText());
        //int summ = Integer.parseInt(diytotal.getText());
       if(ftotal>=1){
            
           
        Object[] row = { qty, "DIY", ftotal};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
        JOptionPane.showMessageDialog(null,"Pizza added!","Info",JOptionPane.INFORMATION_MESSAGE);
       
       MenuUI.tsum.setText(Integer.toString(MenuUI.getSum()));
       
      
       }
       else{
       JOptionPane.showMessageDialog(null,"Empty cart!","Info",JOptionPane.INFORMATION_MESSAGE);
       }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int asparagus1 = (Integer) asparagus.getValue();
        int price=20;
        int f=price*asparagus1;
        Object[] row = { asparagus1, "Asparagus", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));
        }
        
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int asparagus1 = (Integer) chorizo.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Chorizo", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int asparagus1 = (Integer) bo.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Blk Olives", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int asparagus1 = (Integer) on.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Onion", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int asparagus1 = (Integer) gb.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Grn Bllpper", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int asparagus1 = (Integer) rb.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Red bllpper", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int asparagus1 = (Integer) ham.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Ham", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int asparagus1 = (Integer) spinach.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Spinach", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int asparagus1 = (Integer) chicken.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Chicken", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int asparagus1 = (Integer) pc.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Parmechs chess", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int asparagus1 = (Integer) fc.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Feta cheese", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
        diytotal.setText(Integer.toString(getSum()));}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int asparagus1 = (Integer) bacon.getValue();
        int price=20;
        int f=price*asparagus1;
        String data1="hello", data2="", data3="", data4="";
        Object[] row = { asparagus1, "Bacon", f};
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) diytable.getModel();
        if(asparagus1<=0){
          JOptionPane.showMessageDialog(null,"Enter quantity!","Info",JOptionPane.INFORMATION_MESSAGE);  
        }else{
        model.addRow(row);
         diytotal.setText(Integer.toString(getSum()));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void crispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crispyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crispyActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      int viewIndex = diytable.getSelectedRow();
    if(viewIndex != -1) {
        int modelIndex = diytable.convertRowIndexToModel(viewIndex); // converts the row index in the view to the appropriate index in the model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)diytable.getModel();
        model.removeRow(modelIndex);
        diytotal.setText(Integer.toString(getSum()));
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
       diytotal.setText(Integer.toString(getSum()));// TODO add your handling code here:
    }//GEN-LAST:event_sixActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        diytotal.setText(Integer.toString(getSum()));// TODO add your handling code here:
    }//GEN-LAST:event_nineActionPerformed

    private void twelveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveActionPerformed
       diytotal.setText(Integer.toString(getSum())); // TODO add your handling code here:
    }//GEN-LAST:event_twelveActionPerformed

    private void diytotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diytotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diytotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaDecoratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaDecoratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaDecoratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaDecoratorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaDecoratorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel as;
    private javax.swing.JSpinner asparagus;
    private javax.swing.JSpinner bacon;
    private javax.swing.JSpinner bo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JSpinner chicken;
    private javax.swing.JSpinner chorizo;
    private javax.swing.JRadioButton crispy;
    private javax.swing.JRadioButton deep;
    public static javax.swing.JTable diytable;
    private javax.swing.JTextField diytotal;
    private javax.swing.JSpinner fc;
    private javax.swing.JSpinner gb;
    private javax.swing.JSpinner ham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JRadioButton nine;
    private javax.swing.JSpinner on;
    private javax.swing.JSpinner pc;
    private javax.swing.JSpinner rb;
    public static javax.swing.JRadioButton six;
    private javax.swing.JSpinner spinach;
    public static javax.swing.JRadioButton twelve;
    // End of variables declaration//GEN-END:variables
}
