
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gleea
 */
public class PizzaSelectUIhamlovers extends javax.swing.JFrame {

    /**
     * Creates new form PizzaSelect
     */
    public PizzaSelectUIhamlovers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPizzaSize = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        sixCB = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nineCB = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        twelveCB = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        six = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        nine = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        twelve = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(466, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Size/crust");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 200, 25);

        sixCB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(sixCB);
        sixCB.setBounds(110, 210, 40, 34);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("6\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 220, 20, 20);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("9\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 220, 20, 20);

        nineCB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(nineCB);
        nineCB.setBounds(190, 210, 40, 34);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("12\"");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 220, 30, 20);

        twelveCB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(twelveCB);
        twelveCB.setBounds(270, 210, 40, 34);

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 210, 80, 40);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deepcrust.png"))); // NOI18N
        jLabel6.setText("deep crust");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 50, 170, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Light-Wood-Background.png"))); // NOI18N
        jLabel7.setText("CRISPY BASE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 160, 160, 40);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("6\"");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 100, 20, 20);

        six.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(six);
        six.setBounds(110, 90, 40, 34);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("9\"");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 100, 20, 20);

        nine.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(nine);
        nine.setBounds(190, 90, 40, 34);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("12\"");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 100, 30, 20);

        twelve.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        getContentPane().add(twelve);
        twelve.setBounds(270, 90, 40, 34);

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 90, 80, 40);

        jButton3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton3.setText("DONE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 260, 80, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("$80             $90              $100");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 120, 190, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$80             $90              $100");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 240, 190, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Light-Wood-Background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 470, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   int sixinch = (Integer) sixCB.getValue();
        int nineinch=(Integer) nineCB.getValue();
        int twelveinch=(Integer) twelveCB.getValue();
        int price6=80;
        int price9=90;
        int price12=100;
        
        int finalp6;
        finalp6=price6*sixinch;
        
        int finalp9;
        finalp9=price9*nineinch;
        
        int finalp12;
        finalp12=price12*twelveinch;
        
        
        if(sixinch<=0){
            sixinch=0;
        }else{
            Object[] row = { sixinch, "Ham Lovers(crspybas)6in", finalp6};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+sixinch+"  "+"Ham Lovers(crspybas)"+"  "+"6in\t"+finalp6);
        }
        if(nineinch<=0){
            nineinch=0;
        }else{
            Object[] row = { nineinch, "Ham Lovers(crspybas)9in", finalp9};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+nineinch+"  "+"Ham Lovers(crspybas)"+"  "+"9in\t"+finalp9);
        }
        if(twelveinch<=0){
            twelveinch=0;
        }else{
            Object[] row = { twelveinch, "Ham Lovers(crspybas)12in", finalp12};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch+"  "+"Ham Lovers(crspybas)"+"  "+"12in\t"+finalp12);
        }
        if(twelveinch<=0 && nineinch<=0 && sixinch<=0){
            JOptionPane.showMessageDialog(null,"No pizza added. Enter quanity!","Info",JOptionPane.INFORMATION_MESSAGE);
        }else{
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch);
            
        }
        if(twelveinch>=1 || nineinch>=1 || sixinch>=1){
            JOptionPane.showMessageDialog(null,"Pizza added!","Info",JOptionPane.INFORMATION_MESSAGE);
        }else{
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch);
            
        }      MenuUI.tsum.setText(Integer.toString(MenuUI.getSum())); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int sixinch = (Integer) six.getValue();
        int nineinch=(Integer) nine.getValue();
        int twelveinch=(Integer) twelve.getValue();
        int price6=80;
        int price9=90;
        int price12=100;
        int finalp6;
        finalp6=price6*sixinch;
        
        int finalp9;
        finalp9=price9*nineinch;
        
        int finalp12;
        finalp12=price12*twelveinch;
        
        if(sixinch<=0){
            sixinch=0;
        }else{
            Object[] row = { sixinch, "Ham Lovers(dpcrst)6in", finalp6};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+sixinch+"  "+"Ham Lovers(dpcrst)"+"  "+"6in\t"+finalp6);
        }
        if(nineinch<=0){
            nineinch=0;
        }else{
            Object[] row = { nineinch, "Ham Lovers(dpcrst)9in", finalp9};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+nineinch+"  "+"Ham Lovers(dpcrst)"+"  "+"9in\t"+finalp9);
        }
        if(twelveinch<=0){
            twelveinch=0;
        }else{
            Object[] row = { twelveinch, "Ham Lovers(dpcrst)12in", finalp12};
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) MenuUI.menutable.getModel();
            model.addRow(row);
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch+"  "+"Ham Lovers(dpcrst)"+"  "+"12in\t"+finalp12);
        }
        if(twelveinch<=0 && nineinch<=0 && sixinch<=0){
            JOptionPane.showMessageDialog(null,"No pizza added. Enter quanity!","Info",JOptionPane.INFORMATION_MESSAGE);
        }else{
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch);
            
        }
        if(twelveinch>=1 || nineinch>=1 || sixinch>=1){
            JOptionPane.showMessageDialog(null,"Pizza added!","Info",JOptionPane.INFORMATION_MESSAGE);
        }else{
            //MenuUI.cart.setText(MenuUI.cart.getText() + "\n"+twelveinch);
            
        } MenuUI.tsum.setText(Integer.toString(MenuUI.getSum()));
        //String des=BBQbeef.getDescription();
        
        //BBQbeef bbqbeef=new BBQbeef(bbqbeef.getDescription(),bbqbeef.getCost(),6,sixinch);
        //BBQbeef bbqbeef;
        
              // Grab the String value.
              //.addElement(sixinch);
//Pizza n=new BBQbeef();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaSelectUIbbq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaSelectUIbbq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaSelectUIbbq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaSelectUIbbq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PizzaSelectUIbbq().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPizzaSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner nine;
    private javax.swing.JSpinner nineCB;
    private javax.swing.JSpinner six;
    private javax.swing.JSpinner sixCB;
    private javax.swing.JSpinner twelve;
    private javax.swing.JSpinner twelveCB;
    // End of variables declaration//GEN-END:variables
}
